### ISSUE TITLE
test ergebnis 

### ISSUE THREAD

**Issue by rngtng** [fahrrad-bande/carexit#27]
translate

**Comment by ghost** [comment]
BR:

O convencido: ainda não conseguiu se desapegar do carro, simplesmente porque ele é muito conveniente. Para você, as vantagens de usar seu carro vão muito além de pedalar, e por isso algumas vezes você se pergunta se uma "saída" é possível. Nós gostaríamos de apoiar você nesses primeiros passos - dar um ponto de partida à ideia de usar a bicicleta em vez do carro.
 
###

Os duvidosos: você claramente reconhece os benefícios de pedalar, mas você ainda está atento às consequências dessa mudança para você. Nós garantimos: de bicicleta você pode pedalar quase 100 porcento dos seus percursos na cidade. Continue lendo para descobrir como essa mudança pode acontecer para você.

###

Os inseguros: você acredita na bicicleta como um meio de transporte, mas se se sente inseguro e com medo de pedalar na rua? Então você está no lugar certo. Você não pode mudar de um dia para o outro, portanto tome o tempo que precisar e encontre as pessoas certas para te ajudarem. Nós garantimos a você que o prazer de pedalar é maior do que o medo.

**Comment by ghost** [comment]
GR

Οι πεπεισμένοι: Το αυτοκίνητο είναι ακόμα το μεταφορικό μέσο της επιλογής σας, απλά επειδή είναι βολικό. Για σας τα πλεονεκτήματα του ιδιόκτητου οχήματος ξεπερνούν κατά πολύ αυτά της ποδηλασίας, ωστόσο αναρωτιέστε μερικές φορές, αν αυτή η αλλαγή θα ήταν εφικτή. Πολύ ευχαρίστως να σας υποστηρίξουμε στα πρώτα βήματα – κάντε τώρα την αρχή παίρνοντας το ποδήλατο αντί για το αυτοκίνητο. 

###

Οι σκεπτικοί: Για σας τα πλεονεκτήματα του ποδηλάτου είναι σαφή και ξεκάθαρα, παρ’όλ’αυτά σας τρομάζουν οι επιπτώσεις που θα είχε η αλλαγή στη ζωή σας. Σας διαβεβαιώνουμε: Με το ποδήλατο μπορείτε να φτάσετε σχεδόν στο 100% των προορισμών σας μέσα στην πόλη. Διαβάστε παρακάτω για να μάθετε πώς θα το καταφέρετε. 

###

Οι αβέβαιοι: Πιστεύετε στο ποδήλατο ως μέσο μεταφοράς, αλλά τρομάζετε στην ιδέα να βγείτε στην κίνηση χωρίς την προστασία του αυτοκινήτου; Βρίσκεστε στο σωστό μέρος. Η αλλαγή στον τρόπο μετακίνησής σας δεν θα έρθει από τη μία μέρα στην άλλη. Αφιερώστε χρόνο και βρείτε ομοϊδεάτες στην προσπάθειά σας. Είμαστε βέβαιοι ότι η χαρά της ποδηλασίας θα είναι μεγαλύτερη από τους φόβους σας.
