### ISSUE TITLE
Social Media Profiles

### ISSUE THREAD

**Issue by rngtng** [fahrrad-bande/carexit#4]
- [x] Twitter
- [x] Facebook
- [ ] email

**Comment by ghost** [comment]
www.facebook.com/mitRADgelegenheit
https://twitter.com/mradgbln

**Comment by rngtng** [comment]
@flokiflo email(s) brauche ich noch, thx

**Comment by ghost** [comment]
info@carexit.org <mailto:info@carexit.org>

**Comment by rngtng** [comment]
done with 12b518fd762c32bf8e231f8a056c16a3117b64b9
